# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80c5b4412909ccef78262fa539c68aeb"
name = "subscription-build"
handle = "subscription-build"
application_url = "https://walls-paintings-safari-aluminum.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "subscription-build.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://walls-paintings-safari-aluminum.trycloudflare.com/auth/callback",
  "https://walls-paintings-safari-aluminum.trycloudflare.com/auth/shopify/callback",
  "https://walls-paintings-safari-aluminum.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
